Title (#14)
* Inline Pmpermit + some fixes (#201)

* Inline Pmpermit + some fixes

* some fixes

* 😶

* fix many issues

Co-authored-by: rking32 <sljohnwick@gmail.com>

* A little change to fix "ERROR: No closing quotation" (#203)

This will fix this https://nekobin.com/sayufenose error.

It is caused by the use of apostrophe + s ('s) in  the file name. 
You can reproduce this error by making a directory like `Newton's law of motion/lect1.mp4` . And after giving upload command.

(It will give you error while taking screenshot for lect1.mp4)

* fix gsetup not working with [BOTMODE]

* some fixes in inline pmpermit (#204)

* some fixes

* 😶

* 😶

* no use of {chat} in pm

* 🤷

* Update pmpermit.py

Co-authored-by: rking32 <52490534+rking32@users.noreply.github.com>

* only first owner to auth_chats

* Temporary fix to make google translate work (#206)

Can confirm this solves the error of `AttributeError: 'NoneType' object has no attribute 'group'`

* fix gpsetup issue and add filters support to conv.get_response

Co-authored-by: Krishna-singhal <65902764+Krishna-Singhal@users.noreply.github.com>
Co-authored-by: rking32 <sljohnwick@gmail.com>
Co-authored-by: rking32 <52490534+rking32@users.noreply.github.com>
Co-authored-by: Alexandria C <45006100+unixandria-xda@users.noreply.github.com>